server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /

spring:
  application:
    name: reception
  jpa:
    open-in-view: false
  messages:
    basename: i18n/messages
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/hospital
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  flyway:
    locations: classpath:/db/migration